on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Check for todo0  
      run: '! grep -r "todo0" --exclude-dir=workflows .'
    - name: Check for todo1
      run: '! grep -r "todo1" --exclude-dir=workflows .'
    - name: Check for todo2
      run: '! grep -r "todo2" --exclude-dir=workflows .'
    - name: Check for skip() in tests
      run: '! grep -r "skip(" --exclude-dir=workflows tests/'
    
